// export const StateCodes = {
//     "Alabama": "AL",
//     "Alaska": "AK",
//     "Arizona": "AZ",
//     "Arkansas": "AR",
//     "California": "CA",
//     "Colorado": "CO",
//     "Connecticut": "CT",
//     "Delaware": "DE",
//     "District of Columbia": "DC",
//     "Florida": "FL",
//     "Georgia": "GA",
//     "Guam": "GU",
//     "Hawaii": "HI",
//     "Idaho": "ID",
//     "Illinois": "IL",
//     "Indiana": "IN",
//     "Iowa": "IA",
//     "Kansas": "KS",
//     "Kentucky": "KY",
//     "Louisiana": "LA",
//     "Maine": "ME",
//     "Maryland": "MD",
//     "Massachusetts": "MA",
//     "Michigan": "MI",
//     "Minnesota": "MN",
//     "Mississippi": "MS",
//     "Missouri": "MO",
//     "Montana": "MT",
//     "Nebraska": "NE",
//     "Nevada": "NV",
//     "New Hampshire": "NH",
//     "New Jersey": "NJ",
//     "New Mexico": "NM",
//     "New York": "NY",
//     "North Carolina": "NC",
//     "North Dakota": "ND",
//     "Northern Mariana Islands": "MP",
//     "Ohio": "OH",
//     "Oklahoma": "OK",
//     "Oregon": "OR",
//     "Pennsylvania": "PA",
//     "Puerto Rico": "PR",
//     "Rhode Island": "RI",
//     "South Carolina": "SC",
//     "South Dakota": "SD",
//     "Tennessee": "TN",
//     "Texas": "TX",
//     "Trust Territories": "TT",
//     "Utah": "UT",
//     "Vermont": "VT",
//     "Virgin Islands": "VI",
//     "Virginia": "VA",
//     "Washington": "WA",
//     "West Virginia": "WV",
//     "Wisconsin": "WI",
//     "Wyoming": "WY"
//   }



  export const StateCodes = {
    "AL": "AL",
    "AK": "AK",
    "AZ": "AZ",
    "AR": "AR",
    "CA": "CA",
    "CO": "CO",
    "CT": "CT",
    "DE": "DE",
    "DC": "DC",
    "FL": "FL",
    "GA": "GA",
    "GU": "GU",
    "HI": "HI",
    "ID": "ID",
    "IL": "IL",
    "IN": "IN",
    "IA": "IA",
    "KS": "KS",
    "KY": "KY",
    "LA": "LA",
    "ME": "ME",
    "MD": "MD",
    "MA": "MA",
    "MI": "MI",
    "MN": "MN",
    "MS": "MS",
    "MO": "MO",
    "MT": "MT",
    "NE": "NE",
    "NV": "NV",
    "NH": "NH",
    "NJ": "NJ",
    "NM": "NM",
    "NY": "NY",
    "NC": "NC",
    "ND": "ND",
    "MP": "MP",
    "OH": "OH",
    "OK": "OK",
    "OR": "OR",
    "PA": "PA",
    "PR": "PR",
    "RI": "RI",
    "SC": "SC",
    "SD": "SD",
    "TN": "TN",
    "TX": "TX",
    "TT": "TT",
    "UT": "UT",
    "VT": "VT",
    "VI": "VI",
    "VA": "VA",
    "WA": "WA",
    "WV": "WV",
    "WI": "WI",
    "WY": "WY"
  }
  